services:
  nginx:
    container_name: "nginx"
    hostname: "nginx"
    image: nginx:1.21.6-alpine
    profiles: ["server"]
    restart: "always"
    ports:
      - "8080:8080"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf

  redis:
    container_name: "redis"
    hostname: "redis"
    image: redis:7.0.12-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning

  server:
    image: ghcr.io/antonio-alexander/go-blog-rate-limiting_server:latest
    profiles: ["server"]
    expose:
      - "8080"
    build:
      context: ./
      dockerfile: ./cmd/server/Dockerfile
      args:
        PLATFORM: linux/amd64
        GO_ARCH: amd64
    environment:
      HTTP_ADDRESS: ${HTTP_ADDRESS}
      HTTP_PORT: ${HTTP_PORT:-8080}
      READ_TIMEOUT: ${READ_TIMEOUT:-1}
      WRITE_TIMEOUT: ${WRITE_TIMEOUT:-1}
      ALGORITHM: ${ALGORITHM:-token_memory}
      MAX_TOKENS: ${MAX_TOKENS:-4}
      TOKEN_REPLENISH_S: ${TOKEN_REPLENISH_S:-1} #seconds
      QUEUE_SIZE: ${QUEUE_SIZE:-5}
      LEAK_RATE_MS: ${LEAK_RATE_MS:-500} #milliseconds

  client:
    container_name: client
    hostname: client
    image: ghcr.io/antonio-alexander/go-blog-rate-limiting_client:latest
    profiles: ["client"]
    build:
      context: ./
      dockerfile: ./cmd/client/Dockerfile
      args:
        PLATFORM: linux/amd64
        GO_ARCH: amd64
    environment:
      HTTP_ADDRESS: ${HTTP_ADDRESS:-host.docker.internal}
      HTTP_PORT: ${HTTP_PORT:-8080}
      TIMEOUT: ${TIMEOUT:-60}
      MODE: ${MODE:-multiple_requests}
      NUMBER_OF_REQUESTS: ${NUMBER_OF_REQUESTS:-4}
      NUMBER_OF_APPLICATIONS: ${NUMBER_OF_APPLICATIONS:-2}
      REQUEST_RATE: ${REQUEST_RATE:-1} #seconds
      WAIT: ${WAIT:-1} #seconds
      RETRY: ${RETRY:-true}
      MAX_RETRIES: ${MAX_RETRIES:-2}
